package org.sudharsan.simpleservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2017-06-12T00:52:47.429+05:30
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "http://sudharsan.org/SimpleService/", name = "getDepartmentsService")
@XmlSeeAlso({org.sudharsan.simpleservice.getdepartment.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetDepartmentsService {

    @WebMethod(action = "http://sudharsan.org/SimpleService/getDepartment")
    @WebResult(name = "empDepartmentResponse", targetNamespace = "http://sudharsan.org/SimpleService/getdepartment", partName = "parameters")
    public org.sudharsan.simpleservice.getdepartment.EmpDepartmentResponseType getDepartment(
        @WebParam(partName = "parameters", name = "empDepartmentRequest", targetNamespace = "http://sudharsan.org/SimpleService/getdepartment")
        org.sudharsan.simpleservice.getdepartment.EmpDepartmentRequestType parameters
    );
}
